info:
  configuration: Read From Config Service eurekaclientA.yml
  defaultmessage: this is defaultmessage 读取默认profiles eurekaclientA.yml 20160121
spring:
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
